title: All Divines Feets

# The version of your route. There's no particular format here.
# This will be displayed in the metadata in the settings dialog
version: 1.0

# This is the route itself. Here it points to the main.yaml file we created earlier
route:
  use: ./main.yaml

# Extra configuration.
# The project must define a map to compile properly.
# For now, we will use the Breath of the Wild celer map maintained by Pistonight
config:
  - use: Pistonight/celer-presets/botw/full.yaml

  - icons:
      zelda: https://icons.pistonite.org/icon/character.zelda.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
      sor: https://icons.pistonite.org/icon/location.sor.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
      horse: https://icons.pistonite.org/icon/misc.horse.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
      daruk: https://icons.pistonite.org/icon/character.daruk.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
      shrine-active: https://icons.pistonite.org/icon/shrine.shrine.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
      guardian: https://icons.pistonite.org/icon/misc.flux_construct.none.69a2d5.c1fefe.8c5e28.ffffb5.8c5e28.ffffb5.png
      ruta: https://icons.pistonite.org/icon/location.ruta.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
      blight: https://icons.pistonite.org/icon/character.ganon.none.f24c99.ffc0fa.f24c99.ffc0fa.f24c99.ffc0fa.png
      rudania: https://icons.pistonite.org/icon/location.rudania.none.8c5e28.ffffb5.8c5e28.ffffb5.8c5e28.ffffb5.png
      house: https://icons.pistonite.org/icon/location.house.none.568c28.c8e6af.568c28.c8e6af.568c28.c8e6af.png
      medoh: https://icons.pistonite.org/icon/location.medoh.none.8c5e28.ffffb5.8c5e28.ffffb5.8c5e28.ffffb5.png
      naboris: https://icons.pistonite.org/icon/location.naboris.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
      medoh2: https://icons.pistonite.org/icon/location.medoh.none.69a2d5.c1fefe.69a2d5.c1fefe.69a2d5.c1fefe.png
      

  - plugins:
      - use: link
      - use: variables 
  
  - tags:
      active:
        color: cyan
        
        